<?php
define("_NOME", "Nome");
define("_COGNOME", "Cognome");
define("_MESSAGGIO", "Messaggio");
define("_TELEFONO", "Telefono");
define("_PARTENZA", "Partenza");
define("_ARRIVO", "Arrivo");
define("_ADULTI", "Adulti");
define("_BAMBINI", "Bambini");
define("_INDIRIZZO", "Indirizzo");
define("_INDIRIZZO_CONSEGNA", "Indirizzo di consegna");
define("_PIVA", "Partita Iva");
define("_INVIA", "Invia");
define("_OBBLIGATORIO", "Obbligatorio");
define("_RISULTATOIMMAGINE", "Inserisci il codice");
define("_CONSENSO", "Dò il consenso al trattamento dei miei dati");
define("_INFORMATIVA", "Leggi l'informativa");
define("_TEL", "Tel.");
define("_CAP", "Cap");
define("_CITTA", "Città");
define("_NAZIONE", "Nazione");
define("_DATA_NASCITA", "Data di nascita");
define("_LUOGO_NASCITA", "Luogo di nascita");
define("_PAGAMENTO", "Modalità di pagamento");
define("_BONIFICO", "Bonifico Bancario");
define("_CARTA_CREDITO", "PayPal / Carta di Credito");
define("_MOBILE", "Cell.");
define("_CONTINUA", "Continua");
define("_PRODOTTO", "Prodotto");
define("_PRODOTTI", "Prodotti");
define("_TUTTI_PRODOTTI", "Tutti i prodotti");
define("_CODICE", "Codice");
define("_QTA", "Q.tà");
define("_TOTALE", "Totale");
define("_IMPONIBILE_REFUND", "Total amount");
define("_IMPONIBILE", "Imponibile");
define("_IVA", "IVA");
define("_DETRAZIONE", "Detrazione Iva");
define("_IMPORTO_CARRELLO", "Importo carrello");
define("_SPESE_SPEDIZIONE", "Spese di spedizione");
define("_COSTO_CONTRASSEGNO", "Costo contrassegno");
define("_COSTO_CONF_REGALO", "Costo confezione regalo");
define("_SCONTO", "Sconto");
define("_TOTALE_FINALE", "Totale finale");
define("_DETT_SPED", "Dettagli per la spedizione");
define("_DETT_COSTI", "Dettagli costi");
define("_PAGAMENTO_SCELTO", "Modalità pagamento scelta");
define("_DETT_PERS", "Dettagli personali");
define("_WARN_1", "Questo campo è obbligatorio");
define("_WARN_2", "Inserire un indirizzo valido");
define("_WARN_3", "Si è verificato un errore");
define("_WARN_4", "Deve essere uguale alla password");
define("_WARN_5", "Email già registrata");
define("_WARN_6", "Username non esistente");
define("_WARN_7", "Utente non attivo");
define("_WARN_8", "Password errata");
define("_WARN_9", "Per accedere a questa pagina devi essere loggato!");
define("_WARN_10", "Username già utilizzata!");
define("_WARN_11", "Non hai inserito la nuova password!");
define("_WARN_12", "Email non registrata!");
define("_WARN_13", "Il prodotto non è attualmente in stock e non è pertanto acquistabile!");
define("_WARN_14", "Per poter inserire questo prodotto nella lista dei desideri devi prima <br><a href='/login.php'>effettuare il login</a>");
define("_WARN_15", "Per poter inserire un codice sconto è necessario essere registrati nel sistema!");
define("_WARN_16", "Coupon già utilizzato");
define("_WARN_17", "Coupon scaduto");
define("_WARN_19", "Coupon non valido oggi");
define("_WARN_18", "Coupon inesistente");
define("_COOKIES_MSG_1", "Questo sito utilizza cookies per migliorare l'esperienza di navigazione (vedi ");
define("_COOKIES_MSG_2","Continuando la navigazione, accetti l'utilizzo dei cookies ");
define("_ALL_RIGHTS_RESERVED","Tutti i diritti riservati");
define("_VINO", "Vino");
define("_OLIO", "Olio");
define("_SLIDER_1", "16 appartamenti<br />finemente arredati");
define("_SLIDER_2", "in un affascinante paesaggio");
define("_SLIDER_3", "produzione vino e olio");
define("_SLIDER_4", "per una vacanza di relax ...");
define("_SLIDER_5", "...e arte");
define("_CONTACTS_US","Contattaci per informazioni e prenotazioni");

define("_FIRENZE", "Firenze");
define("_ITALIA","Italia");
define("_TOSCANA","Toscana");
define("_APPARTAMENTI", "Appartamenti");
define("_ATTIVITA", "Attività");
define("_SEARCH", "Cerca");
define("_CONTATTI","Contatti");
define("_REGISTRAZIONE", "Registrazione");
define("_REGISTRAZIONE_MSG_1", "Registrazione effettuata con successo!");
define("_ACCOUNT_MSG_1", "Modifica effettuata con successo!");
define("_ACCOUNT_MSG_2", "Successo! A breve riceverà un email con la password!");
define("_PREZZOBASSO","Prezzo dal più basso");
define("_PREZZOALTO","Prezzo dal più alto");
define("_NOME_A_Z","Nome del prodotto: dalla A alla Z");
define("_CODE_A_Z","Codice prodotto: dalla A alla Z");
define("_NOME_Z_A","Nome del prodotto: dalla Z alla A");
define("_ADDCARRELLO","Prodotto inserito con successo nel carrello!");
define("_ADDWISHLIST","Prodotto inserito con successo nella lista dei desideri!");
define("_ADDCOUPON","Coupon inserito con successo!");
define("_ADDNEWSLETTER","Grazie per esserti iscritto  alla nostra newsletter!");
define("_ALREADYINNEWSLETTER", "Sei già iscritto alla nostra newsletter!");
define("_CONF_REGALO", "confezione ragalo 5&euro;<br> (carta regalo e busta personalizzate Marili’s company)");
define("_RIDIGITA_PASS", "Ridigita password");
define("_MODIFICA_PASS", "Modifica la password");
define("_VECCHIA_PASS", "Vecchia password");
define("_NUOVA_PASS", "Nuova password");
define("_REGISTRATI", "Registrati");
define("_IN_PELLE","In pelle");
define("_IN_OTTONE","In ottone");
define("_IN_METALLO","In metallo");
define("_IN_METALLO_PITTURATI","In metallo pitturati");
define("_IN_RESINA_PITTURATI","In resina pitturati");
define("_IN_RESINA_PELTRO","In peltro pitturati");
define("_IN_LEGNO","In legno");
define("_IN_LEGNO_PREGIATO","In legno pregiato");
define("_IN_LEGNO_LACCATO","In legno laccato");
define("_IN_ALTRI_MATERIALI","In altri materiali");
define("_IN_RADICA","In radica");
define("_IN_ALABASTRO","In legno pregiato con top in alabastro");
define("_IN_SIMILCUOIO","In similcuoio");
define("_IN_LEGNO_METALLO","Legno laccato bianco/nero");
define("_OLTRE","Oltre");
define("_SET_TRADIZIONALI","Set Tradizionali da Gioco");
define("_SET_CLASSICI","Set Classici");
define("_SET_MODERNI","Set Moderni");
define("_SET_A_TEMA","Set a Tema (battaglie o personaggi famosi)");
define("_MATERIALE_SCACCHI","Materiale Scacchi");
define("_MATERIALE_SCACCHIERA","Materiale Scacchiera");
define("_STILE","Stile");
define("_PREZZO","Prezzo");

define("_CARRELLO", "CARRELLO");
define("_CARRELLO_MSG","Prodotti nel tuo carrello");
define("_CARRELLO_MSG2","Non ci sono prodotti nel tuo carrello");
?>