<?php
define("_NOME", "Nome e Sobrenome");
define("_COGNOME", "Surname");
define("_MESSAGGIO", "Texto");
define("_TELEFONO", "Phone");
define("_PARTENZA", "Departure");
define("_ARRIVO", "Arrival");
define("_ADULTI", "Adults");
define("_BAMBINI", "Children");
define("_INDIRIZZO", "Address");
define("_INDIRIZZO_CONSEGNA", "Delivery address");
define("_PIVA", "Vat");
define("_INVIA", "Enviar");
define("_OBBLIGATORIO", "Campos obrigatórios");
define("_RISULTATOIMMAGINE", "Ingrese el código");
define("_CONSENSO", "Eu consentimento para o tratamento dos meus dados");
define("_INFORMATIVA", "Privacy");
define("_TEL", "Phone");
define("_CAP", "Postal code");
define("_CITTA", "City");
define("_NAZIONE", "Country");
define("_DATA_NASCITA", "Date of birth");
define("_LUOGO_NASCITA", "Birth place");
define("_PAGAMENTO", "Payment types");
define("_BONIFICO", "Bank transfer");
define("_CARTA_CREDITO", "PayPal / Credit card");
define("_MOBILE", "Mobile");
define("_CONTINUA", "Continue");
define("_PRODOTTO", "Product");
define("_PRODOTTI", "Products");
define("_TUTTI_PRODOTTI", "All the items");
define("_CODICE", "Code");
define("_QTA", "Q.ty");
define("_TOTALE", "Total");
define("_IMPONIBILE", "Taxable amount");
define("_IVA", "Taxes");
define("_DETRAZIONE", "Tax refund");
define("_IMPORTO_CARRELLO", "Cart amount");
define("_SPESE_SPEDIZIONE", "Shipping charges");
define("_COSTO_CONTRASSEGNO", "Cash on delivery charges");
define("_COSTO_CONF_REGALO", "Gift packaging costs");
define("_SCONTO", "Discount");
define("_TOTALE_FINALE", "Final amount");
define("_DETT_SPED", "Shipping details");
define("_DETT_COSTI", "Costs details");
define("_PAGAMENTO_SCELTO", "Chosen payment method");
define("_DETT_PERS", "Personal details");
define("_WARN_1", "Campos obrigatórios");
define("_WARN_2", "Insertar un correo electrónico válido");
define("_WARN_3", "An error accurrred");
define("_WARN_4", "Must be equal to Password");
define("_WARN_5", "Correo electrónico ya registrado");
define("_WARN_6", "Username not found");
define("_WARN_7", "User not active");
define("_WARN_8", "Wrong password");
define("_WARN_9", "To access this page you must be logged!");
define("_WARN_10", "Username already in use!");
define("_WARN_11", "You have not entered the new password!");
define("_WARN_12", "Email not registered!");
define("_WARN_13", "This product is out of stock at the moment and therefore it's not purchasable!");
define("_WARN_14", "To be able to insert a product into your wishlist you need <br><a href='/eng/login.php'>to login first</a>");
define("_WARN_15", "In order to enter a discount code you need to be registered in the system!");
define("_WARN_16", "Coupon already used");
define("_WARN_17", "Coupon expired");
define("_WARN_18", "Coupon does not exist");
define("_COOKIES_MSG_1", "Este sitio utiliza cookies para mejorar la experiencia de navegación (leer");
define("_COOKIES_MSG_2","Si sigue navegando, acepta utilizar nuestras cookies ");
define("_ALL_RIGHTS_RESERVED","All rights reserved");
define("_VINO", "Wine");
define("_OLIO", "Oil");
define("_SLIDER_1", "16 apartments <br />finely furnished");
define("_SLIDER_2", "in a charming landscape");
define("_SLIDER_3", "producing wine and olive oil");
define("_SLIDER_4", "for a relaxing holiday ...");
define("_SLIDER_5", "...and art");
define("_CONTACTS_US","Contact us for information and reservations");

define("_FIRENZE", "Florence");
define("_ITALIA","Italy");
define("_TOSCANA","Tuscany");
define("_APPARTAMENTI", "Apartments");
define("_ATTIVITA", "Activity");
define("_CONTATTI","Contacts");
define("_SEARCH", "Search");
define("_REGISTRAZIONE", "Registration");
define("_REGISTRAZIONE_MSG_1", "You've successfully signed up!");
define("_ACCOUNT_MSG_1", "Changes made!");
define("_ACCOUNT_MSG_2", "Success! You will shortly receive an email with your password!");
define("_PREZZOBASSO","Price: from lowest");
define("_PREZZOALTO","Price: from highest");
define("_NOME_A_Z","Product name: from A to Z");
define("_NOME_Z_A","Product name: from Z to A");
define("_ADDCARRELLO","Product was successfully added to your cart!");
define("_ADDWISHLIST","Product was successfully added to your whislist!");
define("_ADDCOUPON","Coupon successfully placed!");
define("_ADDNEWSLETTER","Gracias por suscribirse a nuestro boletín informativo!");
define("_ALREADYINNEWSLETTER", "Already subscribed to our newsletter!");
define("_CONF_REGALO", "Gift box");
define("_RIDIGITA_PASS", "Re-type password");
define("_MODIFICA_PASS", "Modify password");
define("_VECCHIA_PASS", "Old password");
define("_NUOVA_PASS", "New password");
define("_REGISTRATI", "Sign in");
define("_IN_PELLE","Real leather");
define("_IN_OTTONE","Brass");
define("_IN_METALLO","Metal");
define("_IN_METALLO_PITTURATI","Painted metal");
define("_IN_RESINA_PITTURATI","Painted resin");
define("_IN_RESINA_PELTRO","Painted pewter");
define("_IN_LEGNO","Wood");
define("_IN_LEGNO_PREGIATO","Rare wood");
define("_IN_LEGNO_LACCATO","Lacquered wood");
define("_IN_ALTRI_MATERIALI","Different materials");
define("_IN_RADICA","Briar wood");
define("_IN_ALABASTRO","Wood with top in alabaster");
define("_IN_SIMILCUOIO","Leatherette");
define("_IN_LEGNO_METALLO","Wood finished with metal");
define("_OLTRE","Over");
define("_SET_TRADIZIONALI","Traditional Playing Set");
define("_SET_CLASSICI","Classic Set");
define("_SET_MODERNI","Modern Set");
define("_SET_A_TEMA","Representing Battles or Famous Characters");
define("_MATERIALE_SCACCHI","Chess Man Material");
define("_MATERIALE_SCACCHIERA","Chess Board Material");
define("_STILE","Style");
define("_PREZZO","Price");